### ISSUE TITLE
[ethicapp-v2] Error al iniciar actividad en vista de alumno

### ISSUE THREAD

**Issue by ifgarces** [EthicApp-Development/ethicapp-main#151]
# Descripción del error/bug
Al ejecutar localmente el sistema (docker-compose de desarrollo), en la vista de estudiante, al ingresar el código de una actividad arbitraria en curso, no ocurre nada, se devuelve a la pantalla principal del estudiante, en lugar de navegar hacia la actividad (a la fase correspondiente para responder las preguntas).

https://github.com/EthicApp-Development/ethicapp-main/assets/48460500/55115d3d-f833-42c9-9ea2-4b1f47734b47

# Detalles
## ¿Cuándo ocurrió?
Ocurrió con anterioridad en algunos PRs. Se observó ahora al hacer el merge del PR #143. Sin embargo, el error no parece corresponder a ese PR, por lo que se realizó el merge.

## ¿En qué dispositivo fue?
PC, Linux Mint

## ¿En qué explorador web ocurrió?
Opera 100.0.4815.20

## ¿Cómo reproducir el error?
Lanzar ambiente con `docker-compose` de desarrollo. Autenticarse como profesor, lanzar una actividad, copiar el código, autenticarse como alumno, e intentar ingresar a la actividad mediante ese código.

## Detalles adicionales
Como se muestra en el video, el log del backend al ingresar el código e intentar unirse a la actividad, es el siguiente:

```log
ethicapp-node | [2023-07-01T17:15:54.108Z] Session {
ethicapp-node |   cookie: { path: '/', _expires: null, originalMaxAge: null, httpOnly: true },
ethicapp-node |   passport: {
ethicapp-node |     user: {
ethicapp-node |       id: 3,
ethicapp-node |       name: 'alumno 1',
ethicapp-node |       rut: '20884663-9',
ethicapp-node |       pass: 'f6b16b945f3a595d0f4d0b9270eb0cb5',
ethicapp-node |       mail: 'alumno1@test',
ethicapp-node |       sex: 'M',
ethicapp-node |       role: 'A',
ethicapp-node |       aprendizaje: 'Reflexivo',
ethicapp-node |       lang: 'spanish',
ethicapp-node |       disabled: null
ethicapp-node |     }
ethicapp-node |   },
ethicapp-node |   __lastAccess: 1688231739494,
ethicapp-node |   uid: 3,
ethicapp-node |   role: 'A',
ethicapp-node |   ses: null
ethicapp-node | }
ethicapp-node | [Readings] GET /to-diff?sesid=37 302 - 2.649 ms
ethicapp-node | [Readings] GET /ethics 302 - 1.533 ms
ethicapp-node | [Readings] GET / 302 - 1.378 ms
ethicapp-node | [Readings] GET /seslist 304 - 2.543 ms
ethicapp-node | [Readings] GET /assets/libs/angular.min.js 304 - 0.443 ms
ethicapp-node | [Readings] GET /assets/libs/ui-bootstrap-tpls-1.1.2.min.js 304 - 0.456 ms
ethicapp-node | [Readings] GET /assets/libs/socket.min.js 304 - 0.603 ms
ethicapp-node | [Readings] GET /assets/libs/ua-parser.min.js 304 - 1.024 ms
ethicapp-node | [Readings] GET /assets/libs/angular-intro.min.js 304 - 1.045 ms
ethicapp-node | [Readings] GET /assets/libs/intro.min.js 304 - 1.167 ms
ethicapp-node | [Readings] GET /assets/css/bootstrap.min.css 304 - 0.723 ms
ethicapp-node | [Readings] GET /assets/css/font-awesome.min.css 304 - 0.772 ms
ethicapp-node | [Readings] GET /assets/css/introjs.css 304 - 1.107 ms
ethicapp-node | [Readings] GET /assets/css/main.css 304 - 0.392 ms
ethicapp-node | [Readings] GET /assets/js/ses-ctrl.js 304 - 0.364 ms
ethicapp-node | [2023-07-01T17:15:54.280Z] Error: Not Found
ethicapp-node |     at /home/app/app.js:74:15
ethicapp-node |     at Layer.handle [as handle_request] (/home/app/node_modules/express/lib/router/layer.js:95:5)
ethicapp-node |     at trim_prefix (/home/app/node_modules/express/lib/router/index.js:328:13)
ethicapp-node |     at /home/app/node_modules/express/lib/router/index.js:286:9
ethicapp-node |     at Function.process_params (/home/app/node_modules/express/lib/router/index.js:346:12)
ethicapp-node |     at next (/home/app/node_modules/express/lib/router/index.js:280:10)
ethicapp-node |     at /home/app/node_modules/express/lib/router/index.js:646:15
ethicapp-node |     at next (/home/app/node_modules/express/lib/router/index.js:265:14)
ethicapp-node |     at Function.handle (/home/app/node_modules/express/lib/router/index.js:175:3)
ethicapp-node |     at router (/home/app/node_modules/express/lib/router/index.js:47:12)
ethicapp-node | [Readings] GET /assets/libs/angular.min.js.map 404 - 3.048 ms
ethicapp-node | [2023-07-01T17:15:54.298Z] Error: Not Found
ethicapp-node |     at /home/app/app.js:74:15
ethicapp-node |     at Layer.handle [as handle_request] (/home/app/node_modules/express/lib/router/layer.js:95:5)
ethicapp-node |     at trim_prefix (/home/app/node_modules/express/lib/router/index.js:328:13)
ethicapp-node |     at /home/app/node_modules/express/lib/router/index.js:286:9
ethicapp-node |     at Function.process_params (/home/app/node_modules/express/lib/router/index.js:346:12)
ethicapp-node |     at next (/home/app/node_modules/express/lib/router/index.js:280:10)
ethicapp-node |     at /home/app/node_modules/express/lib/router/index.js:646:15
ethicapp-node |     at next (/home/app/node_modules/express/lib/router/index.js:265:14)
ethicapp-node |     at Function.handle (/home/app/node_modules/express/lib/router/index.js:175:3)
ethicapp-node |     at router (/home/app/node_modules/express/lib/router/index.js:47:12)
ethicapp-node | [Readings] GET /assets/images/logos/logo.png 304 - 0.442 ms
ethicapp-node | [Readings] GET /assets/libs/socket.min.js.map 404 - 2.641 ms
ethicapp-node | [2023-07-01T17:15:54.341Z] Error: Not Found
ethicapp-node |     at /home/app/app.js:74:15
ethicapp-node |     at Layer.handle [as handle_request] (/home/app/node_modules/express/lib/router/layer.js:95:5)
ethicapp-node |     at trim_prefix (/home/app/node_modules/express/lib/router/index.js:328:13)
ethicapp-node |     at /home/app/node_modules/express/lib/router/index.js:286:9
ethicapp-node |     at Function.process_params (/home/app/node_modules/express/lib/router/index.js:346:12)
ethicapp-node |     at next (/home/app/node_modules/express/lib/router/index.js:280:10)
ethicapp-node |     at /home/app/node_modules/express/lib/router/index.js:646:15
ethicapp-node |     at next (/home/app/node_modules/express/lib/router/index.js:265:14)
ethicapp-node |     at Function.handle (/home/app/node_modules/express/lib/router/index.js:175:3)
ethicapp-node |     at router (/home/app/node_modules/express/lib/router/index.js:47:12)
ethicapp-node | [Readings] GET /assets/libs/angular-intro.min.js.map 404 - 2.431 ms
ethicapp-node | [Readings] POST /get-session-list 200 - 5.062 ms
ethicapp-node | [Readings] POST /get-my-name 200 - 4.166 ms
ethicapp-node | [Readings] GET /assets/i18n/ES_CL/spanish.json 304 - 0.333 ms
```

**Comment by mabarraza** [comment]
El issue en questión fue arreglado, los problemas secundarios encontrados serán trabajados en los issues correspondientes.
