### ISSUE TITLE
[ethicapp-v2-ca] Dos respuestas para un mismo request causa caída catastrófica en "/send-diff-selection"

### ISSUE THREAD

**Issue by claudio-alvarez** [EthicApp-Development/ethicapp-main#362]
# Descripción del error/bug

El endpoint de "send-diff-selection" primero llama a una función InitializeContentAnalysis, y luego ejecuta una consulta a la base de datos para guardar la respuesta que envía el usuario cliente, y envía una respuesta HTTP 200 cuando tiene éxito.

InitializeContentAnalysis por su lado verifica si está activado el análisis de contenido en EthicApp. Si el análisis de contenido no está activado, envía una respuesta 503 al cliente. 

Esto último está rompiendo el backend, pues en este mismo flujo se están enviando dos respuestas HTTP. El error específico es que las cabeceras HTTP se están enviando dos veces:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/home/app/node_modules/express/lib/response.js:795:10)
    at ServerResponse.send (/home/app/node_modules/express/lib/response.js:175:12)
    at Result.<anonymous> (/home/app/backend/db/rest-pg.js:118:21)
    at Result.emit (events.js:314:20)
    at Result.emit (domain.js:483:12)
    at Result.handleReadyForQuery (/home/app/node_modules/pg/lib/query.js:146:8)
    at Connection.<anonymous> (/home/app/node_modules/pg/lib/client.js:180:19)
    at Connection.emit (events.js:314:20)
    at Connection.emit (domain.js:483:12) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

Para solucionar el problema, necesitamos:

- Asegurar que solamente desde el controlador se envíen respuestas, y evitar el envío de respuestas desde InitializeContentAnalysis.
- Quizás antes de llamar a InitializeContentAnalysis, debiera haber una llamada a una función que retorne boolean y diga si se requiere o no usar ContentAnalysis, por ejemplo, IsContentAnalysisRequired. Así InitializeContentAnalysis sólo se ejecuta si IsContentAnalysisRequired retorna true. En caso contrario, la ejecución sin análisis de contenido es del todo normal y se retorna finalmente una respuesta 200 al cliente.
- InitializeContentAnalysis debe limitarse a loggear los errores y/o warnings (console.error, console.warn), y propagar excepciones ocurridas al código cliente. El código cliente debe envolver InitializeContentAnalysis en un bloque try-catch y manejar de buena manera las excepciones que ocurran.

# Detalles
## ¿Cuándo ocurrió?
Ocurrió en la prueba grupal realizada el 15/08.

**Comment by claudio-alvarez** [comment]
Estos endpoints legacy han sido todos dados de baja y reimplementados con versiones REST operativas.
